import { expect, test } from 'vitest';
import { createEmptyBoard, playMove, calculateScore } from './goEngine';
import { computeLocalHeuristicMove, computeMctsMove } from '../services/aiService';

test('Simulate full 9x9 AI vs AI game to completion', () => {
  const size = 9;
  let board = createEmptyBoard(size);
  let boardHistory: string[] = [board.map(row => row.map(c => c || '.').join('')).join('')];
  let turn: 'B' | 'W' = 'B';
  let consecutivePasses = 0;
  let moves: { player: 'B' | 'W'; x: number; y: number; isPass: boolean }[] = [];
  let blackCaptured = 0;
  let whiteCaptured = 0;
  
  let moveCount = 0;
  const maxMoves = 150;

  console.log('\n--- Starting 9x9 AI vs AI Simulation ---');

  while (consecutivePasses < 2 && moveCount < maxMoves) {
    const move = computeLocalHeuristicMove(board, turn, boardHistory);
    
    if (move === 'PASS') {
      consecutivePasses++;
      moves.push({ player: turn, x: -1, y: -1, isPass: true });
      console.log(`Move ${moveCount + 1}: Player ${turn} PASS`);
    } else {
      consecutivePasses = 0;
      const res = playMove(board, move.x, move.y, turn, boardHistory);
      if (!res.legal) {
        console.error(`Illegal move generated by AI: (${move.x}, ${move.y}) by ${turn}`);
      }
      expect(res.legal).toBe(true);
      
      board = res.board;
      if (res.captured.length > 0) {
        if (turn === 'B') {
          whiteCaptured += res.captured.length;
        } else {
          blackCaptured += res.captured.length;
        }
        console.log(`Move ${moveCount + 1}: Player ${turn} plays (${move.x}, ${move.y}) - Captured ${res.captured.length} stones`);
      } else {
        console.log(`Move ${moveCount + 1}: Player ${turn} plays (${move.x}, ${move.y})`);
      }
      
      const nextHash = board.map(row => row.map(c => c || '.').join('')).join('');
      boardHistory.push(nextHash);
      moves.push({ player: turn, x: move.x, y: move.y, isPass: false });
    }
    
    turn = turn === 'B' ? 'W' : 'B';
    moveCount++;
  }

  console.log(`\nGame ended after ${moveCount} moves.`);
  console.log(`Final prisoners: Black captured ${whiteCaptured} White stones. White captured ${blackCaptured} Black stones.`);

  // Calculate final score
  const score = calculateScore(board, new Set(), 'Chinese', 7.5, blackCaptured, whiteCaptured);
  console.log(`\nFinal Scores (Chinese Rules, 7.5 Komi):`);
  console.log(`Black Score: ${score.blackScore} (Stones: ${score.blackStonesCount}, Territory: ${score.blackTerritoryCount})`);
  console.log(`White Score: ${score.whiteScore} (Stones: ${score.whiteStonesCount}, Territory: ${score.whiteTerritoryCount}, Komi: 7.5)`);
  console.log(`Winner: ${score.blackScore > score.whiteScore ? 'Black (黑方)' : 'White (白方)'}\n`);

  expect(score.blackScore).toBeGreaterThan(0);
  expect(score.whiteScore).toBeGreaterThan(0);
});

test('Simulate 9x9 MCTS AI vs MCTS AI game to completion (Short search iteration)', () => {
  const size = 9;
  let board = createEmptyBoard(size);
  let boardHistory: string[] = [board.map(row => row.map(c => c || '.').join('')).join('')];
  let turn: 'B' | 'W' = 'B';
  let consecutivePasses = 0;
  let moves: { player: 'B' | 'W'; x: number; y: number; isPass: boolean }[] = [];
  let blackCaptured = 0;
  let whiteCaptured = 0;
  
  let moveCount = 0;
  const maxMoves = 60; // Shorter game length for testing

  console.log('\n--- Starting 9x9 MCTS AI vs MCTS AI Simulation ---');

  while (consecutivePasses < 2 && moveCount < maxMoves) {
    // Run MCTS with 20 iterations for fast test runs
    const move = computeMctsMove(board, turn, boardHistory, 20);
    
    if (move === 'PASS') {
      consecutivePasses++;
      moves.push({ player: turn, x: -1, y: -1, isPass: true });
      console.log(`MCTS Move ${moveCount + 1}: Player ${turn} PASS`);
    } else {
      consecutivePasses = 0;
      const res = playMove(board, move.x, move.y, turn, boardHistory);
      expect(res.legal).toBe(true);
      
      board = res.board;
      if (res.captured.length > 0) {
        if (turn === 'B') {
          whiteCaptured += res.captured.length;
        } else {
          blackCaptured += res.captured.length;
        }
        console.log(`MCTS Move ${moveCount + 1}: Player ${turn} plays (${move.x}, ${move.y}) - Captured ${res.captured.length} stones`);
      } else {
        console.log(`MCTS Move ${moveCount + 1}: Player ${turn} plays (${move.x}, ${move.y})`);
      }
      
      const nextHash = board.map(row => row.map(c => c || '.').join('')).join('');
      boardHistory.push(nextHash);
      moves.push({ player: turn, x: move.x, y: move.y, isPass: false });
    }
    
    turn = turn === 'B' ? 'W' : 'B';
    moveCount++;
  }

  console.log(`\nMCTS Game ended after ${moveCount} moves.`);
  console.log(`Final prisoners: Black captured ${whiteCaptured} White stones. White captured ${blackCaptured} Black stones.`);

  // Calculate final score
  const score = calculateScore(board, new Set(), 'Chinese', 7.5, blackCaptured, whiteCaptured);
  console.log(`\nMCTS Final Scores (Chinese Rules, 7.5 Komi):`);
  console.log(`Black Score: ${score.blackScore} (Stones: ${score.blackStonesCount}, Territory: ${score.blackTerritoryCount})`);
  console.log(`White Score: ${score.whiteScore} (Stones: ${score.whiteStonesCount}, Territory: ${score.whiteTerritoryCount}, Komi: 7.5)`);
  console.log(`Winner: ${score.blackScore > score.whiteScore ? 'Black (黑方)' : 'White (白方)'}\n`);

  expect(score.blackScore).toBeGreaterThan(0);
  expect(score.whiteScore).toBeGreaterThan(0);
}, 20000);
